apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: demo-vote-app
spec:
  selector:
    matchLabels: 
      name: db-deployment
      app: demo-vote-app
  template:
    metadata: 
      name: db-deployment
      labels:
        name: db-deployment
        app: demo-vote-app
    spec: 
      containers:
       - name: db-deployment
         image: postgres:9.4
         ports:
          - containerPort: 80
         env: 
           - name: POSTGRES_HOST_AUTH_METHOD
             value: trust
         volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
      volumes:
       - name: db-data
         emptyDir:
           sizeLimit: 500Mi
