apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: demo-vote-app
spec:
  type: NodePort
  ports:
   - port: 5000
     targetPort: 80
     nodePort: 31000
  selector:
    name: vote-deployment
    app: demo-vote-app  