apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    name: vote-deployment
    app: demo-vote-app
spec:
  selector:
    matchLabels: 
      name: vote-deployment
      app: demo-vote-app

  template:
    metadata: 
      name: vote-deployment
      labels:
        name: vote-deployment
        app: demo-vote-app
    spec: 
      containers:
       - name: vote-deployment
         image: kodekloud/examplevotingapp_vote:before
         ports:
           - containerPort: 80