apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
    app: demo-vote-app
spec:
  selector:
    matchLabels: 
      name: worker
      app: demo-vote-app
  template:
    metadata: 
      name: worker
      labels:
        name: worker
        app: demo-vote-app
    spec: 
      containers:
       - name: worker
         image: kodekloud/examplevotingapp_worker